### ISSUE TITLE
留言评论不了

### ISSUE THREAD

**Issue by MrChenC** [aquanlerou/WeHalo#76]
管理员回复留言正常，帖子里面评论不了

**Comment by manction** [comment]
> 管理员回复留言正常，帖子里面评论不了

+1

**Comment by manction** [comment]
> 管理员回复留言正常，帖子里面评论不了

经验证存在相同的情况。
Halo版本：1.3.2
WeHalo版本：0.1

**Comment by aquanlerou** [comment]
@manction 你那边可能是没有配置好云函数，可以看看是否配置成功，可以看这个视频https://www.bilibili.com/video/BV1s5411Y7Pp?from=search&seid=796683215492399782

**Comment by BennettChina** [comment]
同样遇到文章内无法评论，管理员回复评论功能可用。B站视频也没有看到在文章内评论的测试，我也是看着B站视频配置的WeHalo
Halo版本：1.4.2
WeHalo版本：master

报错信息：
Uncaught (in promise) thirdScriptError
errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message 找不到对应的FunctionName.; at cloud.callFunction api; 
Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message 找不到对应的FunctionName.; at cloud.callFunction api; 
    at new u (http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:254403)
    at d (http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:254910)
    at f (http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:255005)
    at Function.success (http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:412416)
    at http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:129397
    at T (http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:565877)
    at i.<anonymous> (http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:1074542)
    at i.emit (http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:621152)
    at Si (http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:1075484)
    at http://127.0.0.1:60880/appservice/__dev__/WAService.js:2:1076836
errorReport @ VM23 WAService.js:2
thirdErrorReport @ VM23 WAService.js:2
(anonymous) @ VM23 WAService.js:2
f @ VM23 WAService.js:2
i @ VM23 WAService.js:2
(anonymous) @ VM23 WAService.js:2
value @ VM23 WAService.js:2
o @ VM23 WAService.js:2
(anonymous) @ VM23 WAService.js:2

**Comment by aquanlerou** [comment]
cloud.callFunction:fail requestID 云函数那块你是否配置好了对应的数据库ID

**Comment by BennettChina** [comment]
问题解决了，是我没有将另一个msg_sec_check的云函数上传部署，谢谢!
